"""End-to-end materialization tests: parse -> ModelSpec -> get_model_matrix.

Two layers of R-parity coverage:
- `test_model_matrix_matches_r`: live R, diffed directly against
  `model.matrix()` — the strongest check, but skipped if R isn't installed.
- `test_model_matrix_matches_fixture`: the same battery against committed
  CSV fixtures (`tests/parity/fixtures/model_matrix/`, generated by
  `scripts/generate_r_fixtures.py`), so this suite still gets real
  R-parity coverage in CI without requiring R to be installed there.

Both are driven from the same `FIXTURE_CASES` battery in `cases.py`, so
they can't silently drift apart.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import polars as pl
import pytest

from materialize.cases import BOOL_COLS, DF, FACTOR_COLS, FIXTURE_CASES
from parity.r_oracle import R_AVAILABLE, r_model_matrix
from survey_kit_formula.terms.spec import ModelSpec

requires_r = pytest.mark.skipif(not R_AVAILABLE, reason="R is not installed")

FIXTURES_DIR = Path(__file__).parent.parent / "parity" / "fixtures" / "model_matrix"


@requires_r
@pytest.mark.parametrize("slug,formula", FIXTURE_CASES)
def test_model_matrix_matches_r(slug, formula):
    spec = ModelSpec.from_formula(formula, DF)
    ours = spec.get_model_matrix(DF)
    theirs = r_model_matrix(formula, DF, factor_cols=FACTOR_COLS, bool_cols=BOOL_COLS)
    assert ours.shape == theirs.shape, f"{formula}: shape {ours.shape} != {theirs.shape}"
    np.testing.assert_allclose(ours, theirs, atol=1e-8)


@pytest.mark.parametrize("slug,formula", FIXTURE_CASES)
def test_model_matrix_matches_fixture(slug, formula):
    fixture_path = FIXTURES_DIR / f"{slug}.csv"
    if not fixture_path.exists():
        pytest.skip(f"no committed fixture for {slug!r}; run scripts/generate_r_fixtures.py")
    theirs = np.loadtxt(fixture_path, delimiter=",", ndmin=2)
    spec = ModelSpec.from_formula(formula, DF)
    ours = spec.get_model_matrix(DF)
    assert ours.shape == theirs.shape, f"{formula}: shape {ours.shape} != {theirs.shape}"
    np.testing.assert_allclose(ours, theirs, atol=1e-8)


def test_get_model_matrix_reused_on_new_data():
    train = DF.head(8)
    test = DF.tail(4)
    spec = ModelSpec.from_formula("y ~ x + a", train)
    train_mm = spec.get_model_matrix(train)
    test_mm = spec.get_model_matrix(test)
    assert train_mm.shape == (8, spec.total_columns)
    assert test_mm.shape == (4, spec.total_columns)


def test_unseen_level_at_apply_time_raises():
    train = DF.head(8)  # only a1/a2, b1/b2/b3 seen
    spec = ModelSpec.from_formula("y ~ a", train)
    new_df = pl.DataFrame({"y": [1.0], "a": ["a3"]})
    with pytest.raises(ValueError):
        spec.get_model_matrix(new_df)


def test_intercept_column_is_ones():
    spec = ModelSpec.from_formula("y ~ x", DF)
    mm = spec.get_model_matrix(DF)
    np.testing.assert_array_equal(mm[:, 0], np.ones(DF.height))


def test_no_intercept_shape():
    spec = ModelSpec.from_formula("y ~ 0 + x", DF)
    mm = spec.get_model_matrix(DF)
    assert mm.shape == (DF.height, 1)
    np.testing.assert_allclose(mm[:, 0], DF["x"].to_numpy())


@requires_r
def test_ordered_factor_matches_r():
    # A Polars Enum's defined category order is what our ordered() support
    # respects (see terms/spec.py:_extract_levels) -- alphabetical would
    # give the wrong contr.poly ordering (hi < lo < mid) for this column.
    df = DF.with_columns(pl.col("a").cast(pl.String)).with_columns(
        ordv=pl.Series(["lo", "mid", "hi", "lo", "mid", "hi", "lo", "mid", "hi", "lo", "mid", "hi"]).cast(
            pl.Enum(["lo", "mid", "hi"])
        )
    )
    formula = "y ~ ordered(ordv)"
    spec = ModelSpec.from_formula(formula, df)
    (var, fs) = next(iter(spec.factors.items()))
    assert fs.ordered is True
    assert fs.levels == ["lo", "mid", "hi"]

    ours = spec.get_model_matrix(df)

    plain_df = df.with_columns(pl.col("ordv").cast(pl.String))
    theirs = _r_ordered_factor_matrix(plain_df, levels=["lo", "mid", "hi"])
    np.testing.assert_allclose(ours, theirs, atol=1e-8)


def _r_ordered_factor_matrix(df: pl.DataFrame, levels):
    import subprocess
    import tempfile

    script = r"""
args <- commandArgs(trailingOnly = TRUE)
csv_in <- args[1]
levels <- strsplit(args[2], ",", fixed = TRUE)[[1]]
out <- args[3]
d <- read.csv(csv_in, stringsAsFactors = FALSE)
d$ordv <- factor(d$ordv, levels = levels, ordered = TRUE)
mm <- model.matrix(y ~ ordv, data = d)
write.csv(unclass(mm), out, row.names = FALSE)
"""
    with tempfile.NamedTemporaryFile(mode="w", suffix=".R", delete=False) as sf:
        sf.write(script)
        script_path = sf.name
    csv_path = tempfile.NamedTemporaryFile(suffix=".csv", delete=False).name
    df.write_csv(csv_path)
    out_path = tempfile.NamedTemporaryFile(suffix=".csv", delete=False).name
    result = subprocess.run(
        ["Rscript", script_path, csv_path, ",".join(levels), out_path],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(result.stderr)
    return np.loadtxt(out_path, delimiter=",", skiprows=1, ndmin=2)
