from .api import model_frame, model_matrix, required_columns
from .parser import parse_formula
from .terms.spec import ModelSpec

try:
    from ._version import __version__
except ImportError:
    # _version.py is generated by hatch-vcs at build/install time; absent
    # if the package is used directly from a source checkout that was
    # never installed.
    __version__ = "0.0.0+unknown"

__all__ = ["parse_formula", "ModelSpec", "model_matrix", "model_frame", "required_columns", "__version__"]
